server:
  port: 8090

spring:
  application:
    name: Card
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import:
      - "application_prod.yml"
      - "application_qa.yml"
  profiles:
    active:
      - "prod"

logging:
  level:
    root: error
    com.eazybytes: TRACE

build:
  version: 1.0

loans:
  message: "Welcome to EazyBank LOANS DEV related APIs "
  contactDetails:
    name: "Card Owen - developer"
    email: "cards.developer@eazybank.com"
  onCallSupport:
    - (100) 120-1234
    - (100) 573-1375
